### ISSUE TITLE
Create environments for local, dev, and staging

### ISSUE THREAD

**Issue by brinkbrink** [SeattleColleges/belindas-closet-nestjs#10]
As a developer, I will want to ensure that we use different environments for local, development and staging.

**Describe the solution you'd like**\
Create different environments for local, development and staging. 

**Include link(s) to relevant tutorial(s)**\
[NestJS documentation](https://docs.nestjs.com/techniques/configuration)
[Tutorial on Dev.to](https://dev.to/pitops/managing-multiple-environments-in-nestjs-71l)

**Story Points**\
4-6

**Comment by taylorpapke** [comment]
This issue is outdated since we've moved to our new user story format.
