### ISSUE TITLE
Finish user controller, service and model injection

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-nestjs#18]
As a developer, I want to be able to create, read, update and delete users from the site so I can log in and control who else has access.

Describe the problem:
the problem is that I can't log in as a user and use all of the app's features.

Describe the solution you'd like:
CRUD functionality that is testable by Postman at the least.

Include link(s) to relevant tutorial(s):
nestjs basics playlist: https://youtube.com/playlist?list=PL_cUvD4qzbkw-phjGK2qq0nQiG6gw1cKK&feature=shared

nestjs typescript w/ mongodb: https://www.youtube.com/watch?v=4oLUddZVL80&list=PLdAEGQHOerPAMLdJim5Peryj6_2Q-477Z

Describe alternatives you've considered:
none

Is this issue related to any other issues?
#11 #12 #13 

Additional context:
none

Story Points:
4-8

**Comment by brandondombrowsky** [comment]
What Sprint should this be assigned to?

**Comment by taylorpapke** [comment]
Just added to sprint 5. This one should be relatively simple seeing we have implemented in other repos.
