### ISSUE TITLE
Refactor product console.log to use logger

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-nestjs#21]
As a backend developer, I will want to enable logging to view important information about the data transactions occurring.

**Is your feature request related to a problem? Please describe.**\
I'm always frustrated when I can't see why something is not working and console.logs are not completely cutting it.

**Describe the solution you'd like**\
Logs that will more accurately depict what is happening with the data.

**Include link(s) to relevant tutorial(s)**\
https://docs.nestjs.com/techniques/logger

**Describe alternatives you've considered**\
None.

**Is this issue related to any other issues?**\
This issue relates to issue #17 

**Additional context**\

![Image](https://github.com/SeattleColleges/belindas-closet-nestjs/assets/94101953/7b743c3a-7791-4265-b5c9-bc48ec6d7b37)

**Story Points**\
2-4 story points

**Comment by CourtneyHoppus** [comment]
Started research on the built in logging for [NestJS](https://docs.nestjs.com/techniques/logger#use-external-logger) as well as two external logging modules, [Winston](https://github.com/winstonjs/winston) and [Pino](https://github.com/iamolegga/nestjs-pino).
