### ISSUE TITLE
Implement a product data transfer object (DTO)

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-nestjs#23]
As a backend developer, I will want to have a product DTO to allow for easier and simplified data transfer.

**Is your feature request related to a problem? Please describe.**\
I'm always frustrated when I am having issues trying to access data in the backend.

**Describe the solution you'd like**\
A product DTO that will allow for easy access to the data that I need.

**Include link(s) to relevant tutorial(s)**\
https://www.youtube.com/watch?v=6-mBxManIBw&list=PL_cUvD4qzbkw-phjGK2qq0nQiG6gw1cKK&index=6

**Describe alternatives you've considered**\
No alternatives

**Is this issue related to any other issues?**\
"This issue relates to issue #20 

**Additional context**\

![Image](https://github.com/SeattleColleges/belindas-closet-nestjs/assets/94101953/bfc63320-95d2-4744-b8ca-2397dadc38cb)

![Image](https://github.com/SeattleColleges/belindas-closet-nestjs/assets/94101953/2c952dd2-324a-4444-a83d-7d7613ff7ff8)

**Story Points**\
4-8 story points

**Comment by tinpham5614** [comment]
I would like to work on this issue before moving forward with issue #24.
