### ISSUE TITLE
Bug: Update PUT request that return an unexpected message

### ISSUE THREAD

**Issue by tinpham5614** [SeattleColleges/belindas-closet-nestjs#35]
**Describe the bug**\
Currently, update a product method that hasn't checked whether the product exists or not.
The response returns a success message even when the product doesn't exist.

**To Reproduce**\
Add a condition in the PUT request to check if the product exists.

**Expected behavior**\
I want to update the product if it exists or throw an exception if the product with the given id is not found.

**Screenshots**\
![update bug](https://github.com/SeattleColleges/belindas-closet-nestjs/assets/72054441/b5b04803-2ca6-434e-aab0-a0986801f64a)

**Additional context**\
During my test of the admin role feature, I encountered this bug.

**Story Points**\
2

**Comment by CourtneyHoppus** [comment]
@tinpham5614 I have not been able to recreate this bug.
When I try to update a product with an id that doesn't exist in my database, I get the following output:
<img width="900" alt="update_product_id_does_not_exist" src="https://github.com/SeattleColleges/belindas-closet-nestjs/assets/74206103/a00ad8be-f34e-4fab-a260-aa40cecd97b5">

**Comment by tinpham5614** [comment]
@CourtneyHoppus There are 2 error cases:
1. The bug you mentioned is because the id missing one character then we caught the error with the message above. (incorrect id format)
```
catch (error) {
    return response.status(HttpStatus.NOT_FOUND).json({
      message: "Failed to update product, please try again",
      error: error.message,
});
```
2. If you test with the correct ID and replace any character, it will return the successful update message.
For example:
Correct ID: 653a25aa2b77bc903ae022b9
Replace the last character: 653a25aa2b77bc903ae022b2
The result:
![bug](https://github.com/SeattleColleges/belindas-closet-nestjs/assets/72054441/c1476b37-c1a5-4fd7-afd4-8b729735f922)

**Comment by CourtneyHoppus** [comment]
@tinpham5614 I still get the same error
with correct id:
<img width="900" alt="correct_id" src="https://github.com/SeattleColleges/belindas-closet-nestjs/assets/74206103/40cc361a-5dd3-47c3-b757-4ea4f34dc236">

with last character removed:
<img width="900" alt="last_character_removed" src="https://github.com/SeattleColleges/belindas-closet-nestjs/assets/74206103/b27483df-e765-4521-96f7-9337dc10943f">

with last character changed:
<img width="900" alt="last_character_changed" src="https://github.com/SeattleColleges/belindas-closet-nestjs/assets/74206103/fc4cb81c-14f7-45f3-b730-1674b828ca76">

**Comment by tinpham5614** [comment]
That's interesting. 😄
