### ISSUE TITLE
Refactor: Add User DTOs

### ISSUE THREAD

**Issue by CourtneyHoppus** [SeattleColleges/belindas-closet-nestjs#50]
As a developer, I want to have the User Entity to have a Data Transfer Objects (DTO) for updating a user.

The User [Controller](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/user/controllers/user/user.controller.ts) and User [Service](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/user/services/user/user.service.ts) method `addUser` are redundant, the Auth module creates new users with the sign-up methods in the Auth [Controller](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/auth/controllers/auth.controller.ts) and [Service](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/auth/services/auth.service.ts) with a [DTO](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/auth/dto/signup.dto.ts). I propose removing these methods.

This will make our coding styles the same across this project and in conjunction with NSC Events.

A `update-user.dto` object should be created.

This issue relates to issue #47

**Comment by tinpham5614** [comment]
Yes, I agree.
addUser is redundant since we created sign-up already.
